#!/bin/sh
#SBATCH --job-name=cc269_panaroo
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=6
#SBATCH --mem=32G
#SBATCH --cluster=htc
#SBATCH --partition=short
#SBATCH --time=12:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=XXX
#SBATCH --output=/data/zool-bactgenomics/kebl7130/panaroo/panaroo_slurm_outputs/panaroo_job_%j.out
#SBATCH --error=/data/zool-bactgenomics/kebl7130/panaroo/panaroo_slurm_outputs/panaroo_job_%j.err

# Prepare the environment
module purge
module load panaroo/1.3.2-foss-2021b

# Run Panaroo
panaroo -i /data/zool-bactgenomics/kebl7130/panaroo/gff3_file_path_list.txt \
        -o /data/zool-bactgenomics/kebl7130/panaroo/panaroo_output_two \
        -a core \
        --core_threshold 0.95 \
        -t 6 \
        --clean-mode strict \
        --remove-invalid-genes

